"""empty message

Revision ID: 012bd2dd1f71
Revises: 17b8de655ec6
Create Date: 2020-10-06 13:52:54.211791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012bd2dd1f71'
down_revision = '17b8de655ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('address', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'address')
    # ### end Alembic commands ###
